# --- Experiment Tracking ---
experiment_name: "SIDE_Ablation_Study"

# --- Model Configuration ---
model:
  # Encoder settings
  encoder:
    name: "models.simple_unet.Encoder"

  # Decoder settings
  decoders:
    segmentation:
      name: "models.simple_unet.SegmentationDecoder"
      params:
        num_classes: 2

    #disparity:
    #  name: "models.simple_unet.Decoder"
    #  params:
    #    num_classes: 1

# --- Data Configuration ---
dataset:
  name: "CholecSeg8k"

# --- Training Configuration ---
training:
  epochs: 100
  batch_size: 8
  loss_weights:
    segmentation: 1.0
    disparity: 0.5

  # Criterion settings
  criterion:
    name: "monai.losses.DiceCELoss"
    params:
      sigmoid: True

  # Optimizer settings
  optimizer:
    lr: 0.0001
    weight_decay: 0.01

  # Learning rate scheduler settings
  scheduler:
    factor: 0.1 # Factor by which the learning rate will be reduced
    patience: 10 # Number of epochs with no improvement after which learning rate will be reduced

  # Knowledge Distillation settings
  teachers:
    - "/path/to/teacher_model_1.pth"
    - "/path/to/teacher_model_2.pth"

misc:
  seed: 42